### ISSUE TITLE
Remote Container Plugin icon

### ISSUE THREAD

**Issue by jeffythedragonslayer** [werkn/n64devkit-everdrive#2]
Hi, I'm trying to follow these instructions for N64 development and can't find this icon.  Can you screensnip what it's supposed to look like?

> Launch VSCode and verify that the editor has the Remote Container Plugin installed. It will be an icon that looks like computer on listed along the left-hand side in the same place as the Explorer / Extensions icons.

**Comment by werkn** [comment]
@jeffythedragonslayer I attached a quick screengrab of what I think your looking for.  If it is I'll add it to the README.

![image](https://user-images.githubusercontent.com/10902433/141507483-4df5f053-73c3-4f7a-a522-91ac21dd0c66.png)

The README may be a bit out of date as the library I'm using (Libdragon) has gone through a ton of changes lately, if you hit any more sticking points let me know.

**Comment by jeffythedragonslayer** [comment]
Got it - thanks.
