### ISSUE TITLE
.z64 into emu

### ISSUE THREAD

**Issue by jeffythedragonslayer** [werkn/n64devkit-everdrive#3]
Hi, I do not yet have a flashcart.  Do you know the best way to get the .z64 into an emulator from the docker container?

**Comment by werkn** [comment]
I've got a little blog post on using CEN64/PowerShell for this, check out https://werkn.github.io/posts/setup-cen64/.  Basically I setup CEN64 to run the built .z64 using PowerShell commands.

**Comment by werkn** [comment]
CEN64 will be fine for most of the development, you don't need a flashcart right away but there are times when CEN64 will run a ROM that does not work on the N64.  

It's also been my experience that performance between the emulator and the actual console differs a lot (framerates / audio).  

**If you want to go the emulation route maybe try the Official SDK which works great with emulators.**  I can hook you up with the N64 Brew Discord which has a ton of people using the Official SDK.

**Comment by jeffythedragonslayer** [comment]
I'm confused.  Judging by the tilde in this path in step 2:

`~/n64/cen64/`

It looks like that is supposed to be *nix system, but step 1 said this is about windows.

**Comment by werkn** [comment]
~/n64/cen64 works on Windows 10 as a path in PowerShell.  It's just similar syntax to Bash/Linux.  The folder you want to create is looks like this (replace 'werkn') with your username.

![image](https://user-images.githubusercontent.com/10902433/141513223-01bb5150-692f-4655-91ad-ff4843acab68.png)

**Comment by jeffythedragonslayer** [comment]
Ah ok, thanks.  I'm also going to be on Project 64 for now since I'm not able to dump my pifdata.bin yet either.

**Comment by werkn** [comment]
If you want to try again add me on Discord and I can walk through the setup.

werkn#8963
